### ISSUE TITLE
Crypto: Static IV

### ISSUE THREAD

**Issue by terrorbyte** [bbq-research/DSCv3#5]
# Problem
Initialization Vector is static - https://github.com/bbq-research/DSCv3/blob/master/crypto.py#L13

# Impact
* Replay attacks are trivial
* Oracle attacks

# Solution
Generate a random IV every single crypto message and define a known length for the spec to extract it.

**Comment by scottrcarlson** [comment]
Thank you for looking into this. 

The AES implementation was put in place to push forward on the rest of the system implementation and testing. We will be replacing with a proper ChaCha20/Poly1305 AEAD implementation per advice.

This will be rolled out in the very near future.
Thanks again!
